# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0197b13b423ae442421ec5466425716379fc62ca79028976c83e166a24638f8a488641bde5e4b5847df7cfaf4170e385b06c43085053e8d55711493ee6f37ce

test:
  secret_key_base: 8d59ff25382f5a45ffa3902f13ca4d15e0636f0f55308b0521fdaeb5d80a5dbfd34268281341a5a81a303ffe6af8c4cad12b3ac89eb955702b867f06c10d27f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
